//
// AbstractCardInfoModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AbstractCardInfoModelAnyOf: Codable, JSONEncodable, Hashable {

    public var cardCategory: CardCategoryInfo?
    public var cardOwnerInfo: UserInfoBase?

    public init(cardCategory: CardCategoryInfo? = nil, cardOwnerInfo: UserInfoBase? = nil) {
        self.cardCategory = cardCategory
        self.cardOwnerInfo = cardOwnerInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardCategory
        case cardOwnerInfo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cardCategory, forKey: .cardCategory)
        try container.encodeIfPresent(cardOwnerInfo, forKey: .cardOwnerInfo)
    }
}

