//
// AcceptTenderOfferViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация о получении согласия с офертой. */
public struct AcceptTenderOfferViewModel: Codable, JSONEncodable, Hashable {

    /** Дата получения согласия с офертой. */
    public var acceptTenderDate: Date?
    public var acceptTenderOfferType: CustomerActionType?
    /** Источник получения согласия. */
    public var acceptTenderOfferTypeSourceId: String?

    public init(acceptTenderDate: Date? = nil, acceptTenderOfferType: CustomerActionType? = nil, acceptTenderOfferTypeSourceId: String? = nil) {
        self.acceptTenderDate = acceptTenderDate
        self.acceptTenderOfferType = acceptTenderOfferType
        self.acceptTenderOfferTypeSourceId = acceptTenderOfferTypeSourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case acceptTenderDate
        case acceptTenderOfferType
        case acceptTenderOfferTypeSourceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(acceptTenderDate, forKey: .acceptTenderDate)
        try container.encodeIfPresent(acceptTenderOfferType, forKey: .acceptTenderOfferType)
        try container.encodeIfPresent(acceptTenderOfferTypeSourceId, forKey: .acceptTenderOfferTypeSourceId)
    }
}

