//
// AccountChangeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountChangeType: String, Codable, CaseIterable {
    case bonusActivation = "BonusActivation"
    case bonusExpiration = "BonusExpiration"
}
