//
// ActionTypeModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ActionTypeModel: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var description: String?
    public var isDeleted: Bool?
    public var logicalName: String?

    public init(id: Int? = nil, name: String? = nil, description: String? = nil, isDeleted: Bool? = nil, logicalName: String? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.isDeleted = isDeleted
        self.logicalName = logicalName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case isDeleted
        case logicalName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(logicalName, forKey: .logicalName)
    }
}

