//
// AnswerHandlerViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель обработчика ответа. */
public struct AnswerHandlerViewModel: Codable, JSONEncodable, Hashable {

    /** Отметка о выборе обработчика ответа (true — выбран, false — не выбран). */
    public var isSelected: Bool?
    public var handlerType: AnswerHandlerType?
    /** Дополнительные поля обработчика. */
    public var fields: [AnswerHandlerFieldViewModel]?

    public init(isSelected: Bool? = nil, handlerType: AnswerHandlerType? = nil, fields: [AnswerHandlerFieldViewModel]? = nil) {
        self.isSelected = isSelected
        self.handlerType = handlerType
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSelected
        case handlerType
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isSelected, forKey: .isSelected)
        try container.encodeIfPresent(handlerType, forKey: .handlerType)
        try container.encodeIfPresent(fields, forKey: .fields)
    }
}

