//
// CalculatorFilterViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CalculatorFilterViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Id калькулятора. */
    public var calculatorId: Int?

    public init(calculatorId: Int? = nil) {
        self.calculatorId = calculatorId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calculatorId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(calculatorId, forKey: .calculatorId)
    }
}

