//
// CampaignPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Разрешения на просмотр связанных объектов кампании. */
public struct CampaignPermissions: Codable, JSONEncodable, Hashable {

    /** Значение, определяющее, есть ли разрешение на акции. */
    public var offers: Bool?
    /** Значение, определяющее, есть ли разрешение на рассылки. */
    public var mailings: Bool?
    /** Значение, определяющее, есть ли разрешение на показатели. */
    public var metrics: Bool?
    /** Значение, определяющее, есть ли разрешение на просмотр брендов (рекламные материалы). */
    public var brands: Bool?
    /** Значение, определяющее, есть ли разрешение на просмотр начислений и списаний. */
    public var cardDeposits: Bool?

    public init(offers: Bool? = nil, mailings: Bool? = nil, metrics: Bool? = nil, brands: Bool? = nil, cardDeposits: Bool? = nil) {
        self.offers = offers
        self.mailings = mailings
        self.metrics = metrics
        self.brands = brands
        self.cardDeposits = cardDeposits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offers
        case mailings
        case metrics
        case brands
        case cardDeposits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(offers, forKey: .offers)
        try container.encodeIfPresent(mailings, forKey: .mailings)
        try container.encodeIfPresent(metrics, forKey: .metrics)
        try container.encodeIfPresent(brands, forKey: .brands)
        try container.encodeIfPresent(cardDeposits, forKey: .cardDeposits)
    }
}

