//
// CheckBoughtListResultModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckBoughtListResultModel: Codable, JSONEncodable, Hashable {

    public var goodsID: String?
    public var isBought: Bool?

    public init(goodsID: String? = nil, isBought: Bool? = nil) {
        self.goodsID = goodsID
        self.isBought = isBought
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goodsID
        case isBought
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goodsID, forKey: .goodsID)
        try container.encodeIfPresent(isBought, forKey: .isBought)
    }
}

