//
// ChequeResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация о примененных расчетах в чеке. */
public struct ChequeResponseModel: Codable, JSONEncodable, Hashable {

    /** Сумма по чеку до применения скидок. */
    public var totalAmount: Double?
    /** Прямая скидка по чеку до применения скидок. */
    public var totalDiscount: Double?
    /** Кешбэк по чеку. */
    public var totalCashback: Double?
    /** Позиции в чеке. */
    public var lines: [ChequeLineResponseModel]?

    public init(totalAmount: Double? = nil, totalDiscount: Double? = nil, totalCashback: Double? = nil, lines: [ChequeLineResponseModel]? = nil) {
        self.totalAmount = totalAmount
        self.totalDiscount = totalDiscount
        self.totalCashback = totalCashback
        self.lines = lines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalAmount
        case totalDiscount
        case totalCashback
        case lines
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalAmount, forKey: .totalAmount)
        try container.encodeIfPresent(totalDiscount, forKey: .totalDiscount)
        try container.encodeIfPresent(totalCashback, forKey: .totalCashback)
        try container.encodeIfPresent(lines, forKey: .lines)
    }
}

