//
// ChequePositionGoodsFilterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Фильтр \&quot;Товар\&quot;. */
public struct ChequePositionGoodsFilterDto: Codable, JSONEncodable, Hashable {

    /** Имя фильтра. */
    public var name: String?
    /** Параметры обработки. */
    public var processParameters: String?
    /** Группы товаров. */
    public var goodsGroups: [AnyCodable]?
    /** Логическое имя атрибута \"Персональное предложение\". */
    public var personalOfferAttributeLogicalName: String?
    public var type: ChequeGoodsFilterType?
    public var _operator: ComparisonOperator?
    /** Первое значение для операции. */
    public var firstValue: Double?
    /** Второе значение для операции. */
    public var secondValue: Double?
    /** Делить позиции по условиям. */
    public var dividePositions: Bool?
    public var chequeGoodsSortType: ChequeGoodsSortType?

    public init(name: String? = nil, processParameters: String? = nil, goodsGroups: [AnyCodable]? = nil, personalOfferAttributeLogicalName: String? = nil, type: ChequeGoodsFilterType? = nil, _operator: ComparisonOperator? = nil, firstValue: Double? = nil, secondValue: Double? = nil, dividePositions: Bool? = nil, chequeGoodsSortType: ChequeGoodsSortType? = nil) {
        self.name = name
        self.processParameters = processParameters
        self.goodsGroups = goodsGroups
        self.personalOfferAttributeLogicalName = personalOfferAttributeLogicalName
        self.type = type
        self._operator = _operator
        self.firstValue = firstValue
        self.secondValue = secondValue
        self.dividePositions = dividePositions
        self.chequeGoodsSortType = chequeGoodsSortType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case processParameters
        case goodsGroups
        case personalOfferAttributeLogicalName
        case type
        case _operator = "operator"
        case firstValue
        case secondValue
        case dividePositions
        case chequeGoodsSortType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(processParameters, forKey: .processParameters)
        try container.encodeIfPresent(goodsGroups, forKey: .goodsGroups)
        try container.encodeIfPresent(personalOfferAttributeLogicalName, forKey: .personalOfferAttributeLogicalName)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(_operator, forKey: ._operator)
        try container.encodeIfPresent(firstValue, forKey: .firstValue)
        try container.encodeIfPresent(secondValue, forKey: .secondValue)
        try container.encodeIfPresent(dividePositions, forKey: .dividePositions)
        try container.encodeIfPresent(chequeGoodsSortType, forKey: .chequeGoodsSortType)
    }
}

