//
// ChequeGoodsSetType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Поле, по значениям которого будет формироваться набор. */
public enum ChequeGoodsSetType: String, Codable, CaseIterable {
    case quantity = "Quantity"
    case amount = "Amount"
}
