//
// CommonBrandModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommonBrandModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Порядковый номер. */
    public var order: Int?
    public var state: BrandModelState?

    public init(order: Int? = nil, state: BrandModelState? = nil) {
        self.order = order
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(state, forKey: .state)
    }
}

