//
// CorrectionDiscountActionViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** View модель действия \&quot;Корректировка прямой скидки\&quot;. */
public struct CorrectionDiscountActionViewModel: Codable, JSONEncodable, Hashable {

    /** Id действия. Если указан, редактируется действие, иначе создается новое. */
    public var actionId: Int?
    public var actionType: ActionTypeViewModel?
    /** Порядок действия. */
    public var order: Int?
    /** Занчение округления в копейках. */
    public var roundValue: Int?
    public var correctionTypeDiscounts: CorrectionTypeDiscounts?

    public init(actionId: Int? = nil, actionType: ActionTypeViewModel? = nil, order: Int? = nil, roundValue: Int? = nil, correctionTypeDiscounts: CorrectionTypeDiscounts? = nil) {
        self.actionId = actionId
        self.actionType = actionType
        self.order = order
        self.roundValue = roundValue
        self.correctionTypeDiscounts = correctionTypeDiscounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionId
        case actionType
        case order
        case roundValue
        case correctionTypeDiscounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actionId, forKey: .actionId)
        try container.encodeIfPresent(actionType, forKey: .actionType)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(roundValue, forKey: .roundValue)
        try container.encodeIfPresent(correctionTypeDiscounts, forKey: .correctionTypeDiscounts)
    }
}

