//
// CorrectionPaymentActionViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** View модель действия \&quot;Корректировка оплаты\&quot;. */
public struct CorrectionPaymentActionViewModel: Codable, JSONEncodable, Hashable {

    /** Id действия. Если указан, редактируется действие, иначе создается новое. */
    public var actionId: Int?
    public var actionType: ActionTypeViewModel?
    /** Порядок действия. */
    public var order: Int?
    /** Значение округления в копейках. */
    public var roundValue: Int?
    public var target: PaymentCorrectionTargets?

    public init(actionId: Int? = nil, actionType: ActionTypeViewModel? = nil, order: Int? = nil, roundValue: Int? = nil, target: PaymentCorrectionTargets? = nil) {
        self.actionId = actionId
        self.actionType = actionType
        self.order = order
        self.roundValue = roundValue
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionId
        case actionType
        case order
        case roundValue
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actionId, forKey: .actionId)
        try container.encodeIfPresent(actionType, forKey: .actionType)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(roundValue, forKey: .roundValue)
        try container.encodeIfPresent(target, forKey: .target)
    }
}

