//
// CounterTarget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CounterTarget: String, Codable, CaseIterable {
    case eventDateTime = "EventDateTime"
    case sourceDateTime = "SourceDateTime"
    case person = "Person"
    case card = "Card"
    case partner = "Partner"
    case device = "Device"
    case merchant = "Merchant"
    case oauthidentifierinfo = "OAuthIdentifierInfo"
    case oauthactivitytype = "OAuthActivityType"
    case oauthobjectid = "OAuthObjectId"
    case oauthgroupid = "OAuthGroupId"
    case accountGroup = "AccountGroup"
    case refundedPurchase = "RefundedPurchase"
    case referral = "Referral"
    case purchase = "Purchase"
    case legal = "Legal"
    case eventDay = "EventDay"
    case eventMonth = "EventMonth"
    case eventYear = "EventYear"
    case week = "Week"
    case good = "Good"
    case offer = "Offer"
}
