//
// CouponsGenerateModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель генерации купонов. */
public struct CouponsGenerateModel: Codable, JSONEncodable, Hashable {

    /** Внутренний идентификатор выпуска купона. */
    public var emissionId: Int?
    /** Количество купонов для генерации. */
    public var couponsCount: Int?

    public init(emissionId: Int? = nil, couponsCount: Int? = nil) {
        self.emissionId = emissionId
        self.couponsCount = couponsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emissionId
        case couponsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(emissionId, forKey: .emissionId)
        try container.encodeIfPresent(couponsCount, forKey: .couponsCount)
    }
}

