//
// CouponIssueActionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Действие акции \&quot;Выдача купона\&quot;. */
public struct CouponIssueActionDto: Codable, JSONEncodable, Hashable {

    /** Порядковый номер действия в цепочке. */
    public var order: Int?
    /** Id действия в цепочке. */
    public var id: String?
    /** Идентификатор выпуска. */
    public var couponEmissionId: Int?
    /** Количество выдаваемых купонов. */
    public var issueCount: Int?

    public init(order: Int? = nil, id: String? = nil, couponEmissionId: Int? = nil, issueCount: Int? = nil) {
        self.order = order
        self.id = id
        self.couponEmissionId = couponEmissionId
        self.issueCount = issueCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case id
        case couponEmissionId
        case issueCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(couponEmissionId, forKey: .couponEmissionId)
        try container.encodeIfPresent(issueCount, forKey: .issueCount)
    }
}

