//
// CreateUserModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель для регистрации в системе нового пользователя. */
public struct CreateUserModel: Codable, JSONEncodable, Hashable {

    /** Логин пользователя. */
    public var login: String?
    /** Пароль пользователя. */
    public var password: String?
    /** Ид программы лояльности. */
    public var loyaltyProgramId: Int?

    public init(login: String? = nil, password: String? = nil, loyaltyProgramId: Int? = nil) {
        self.login = login
        self.password = password
        self.loyaltyProgramId = loyaltyProgramId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case login
        case password
        case loyaltyProgramId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(login, forKey: .login)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(loyaltyProgramId, forKey: .loyaltyProgramId)
    }
}

