//
// DateMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Mode. */
public enum DateMode: String, Codable, CaseIterable {
    case calendar = "Calendar"
    case float = "Float"
}
