//
// DeletedActionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Удаленное действие. */
public struct DeletedActionDto: Codable, JSONEncodable, Hashable {

    /** Порядковый номер действия в цепочке. */
    public var order: Int?
    /** Id действия в цепочке. */
    public var id: String?
    /** Шаблон сообщения. */
    public var logicalName: String?
    /** Шаблон сообщения. */
    public var name: String?

    public init(order: Int? = nil, id: String? = nil, logicalName: String? = nil, name: String? = nil) {
        self.order = order
        self.id = id
        self.logicalName = logicalName
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case id
        case logicalName
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(logicalName, forKey: .logicalName)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

