//
// DeviceBriefViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeviceBriefViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Название устройства. */
    public var name: String?
    /** Статус устройства (true — архивный, false — неархивный). */
    public var isDeleted: Bool?
    /** Внутренний идентификатор Партнера. */
    public var partnerId: Int?
    /** Внутренний идентификатор магазина. */
    public var merchantId: Int?

    public init(name: String? = nil, isDeleted: Bool? = nil, partnerId: Int? = nil, merchantId: Int? = nil) {
        self.name = name
        self.isDeleted = isDeleted
        self.partnerId = partnerId
        self.merchantId = merchantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case isDeleted
        case partnerId
        case merchantId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(partnerId, forKey: .partnerId)
        try container.encodeIfPresent(merchantId, forKey: .merchantId)
    }
}

