//
// DeviceEmulationCashPaymentModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель добавления оплаты. */
public struct DeviceEmulationCashPaymentModel: Codable, JSONEncodable, Hashable {

    /** Сумма. */
    public var cashAmount: Double?

    public init(cashAmount: Double? = nil) {
        self.cashAmount = cashAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cashAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cashAmount, forKey: .cashAmount)
    }
}

