//
// FilterModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Результат фильтрации. */
public struct FilterModel: Codable, JSONEncodable, Hashable {

    /** Идентификатор фильтра. */
    public var id: Int?
    /** Наименование фильтра. */
    public var name: String?
    /** Значение фильтрации. */
    public var checkValue: Bool?
    /** Детали фильтрации. */
    public var checkDetails: String?
    /** Длительность расчета в миллисекундах. */
    public var calculationDuration: Double?

    public init(id: Int? = nil, name: String? = nil, checkValue: Bool? = nil, checkDetails: String? = nil, calculationDuration: Double? = nil) {
        self.id = id
        self.name = name
        self.checkValue = checkValue
        self.checkDetails = checkDetails
        self.calculationDuration = calculationDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case checkValue
        case checkDetails
        case calculationDuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(checkValue, forKey: .checkValue)
        try container.encodeIfPresent(checkDetails, forKey: .checkDetails)
        try container.encodeIfPresent(calculationDuration, forKey: .calculationDuration)
    }
}

