//
// FinishRegistrationResultAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FinishRegistrationResultAnyOf: Codable, JSONEncodable, Hashable {

    /** Закончена ли регистрация пользователя. */
    public var registrationCompleted: Bool?
    /** Список невыполненых действий клиента. */
    public var uncompletedActions: [UserActionModel]?
    /** Новый токен для зарегистрированного пользователя. */
    public var authToken: String?

    public init(registrationCompleted: Bool? = nil, uncompletedActions: [UserActionModel]? = nil, authToken: String? = nil) {
        self.registrationCompleted = registrationCompleted
        self.uncompletedActions = uncompletedActions
        self.authToken = authToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case registrationCompleted
        case uncompletedActions
        case authToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(registrationCompleted, forKey: .registrationCompleted)
        try container.encodeIfPresent(uncompletedActions, forKey: .uncompletedActions)
        try container.encodeIfPresent(authToken, forKey: .authToken)
    }
}

