//
// FixedPurchaseFilterPeriodViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FixedPurchaseFilterPeriodViewModelAnyOf: Codable, JSONEncodable, Hashable {

    public var dateOperation: FilterOperation?
    /** Первое значение даты покупки. */
    public var dateFirstValue: Date?
    /** Второе значение даты покупки. */
    public var dateSecondValue: Date?

    public init(dateOperation: FilterOperation? = nil, dateFirstValue: Date? = nil, dateSecondValue: Date? = nil) {
        self.dateOperation = dateOperation
        self.dateFirstValue = dateFirstValue
        self.dateSecondValue = dateSecondValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dateOperation
        case dateFirstValue
        case dateSecondValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dateOperation, forKey: .dateOperation)
        try container.encodeIfPresent(dateFirstValue, forKey: .dateFirstValue)
        try container.encodeIfPresent(dateSecondValue, forKey: .dateSecondValue)
    }
}

