//
// GetOfferFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель фильтра для получения модели одной акции. */
public struct GetOfferFilter: Codable, JSONEncodable, Hashable {

    /** Id акции. */
    public var offerId: Int?
    public var mode: ViewMode?

    public init(offerId: Int? = nil, mode: ViewMode? = nil) {
        self.offerId = offerId
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offerId
        case mode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(offerId, forKey: .offerId)
        try container.encodeIfPresent(mode, forKey: .mode)
    }
}

