//
// GoodsSetItemInfoViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация о составляющей набора. */
public struct GoodsSetItemInfoViewModel: Codable, JSONEncodable, Hashable {

    public var goodsGroup: GoodsGroupViewModel?
    /** Значение для добавления в набор. */
    public var value: Double?
    /** Флаг необходимости формировать набор только из одинаковых товаров. */
    public var useSameGoods: Bool?

    public init(goodsGroup: GoodsGroupViewModel? = nil, value: Double? = nil, useSameGoods: Bool? = nil) {
        self.goodsGroup = goodsGroup
        self.value = value
        self.useSameGoods = useSameGoods
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goodsGroup
        case value
        case useSameGoods
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goodsGroup, forKey: .goodsGroup)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(useSameGoods, forKey: .useSameGoods)
    }
}

