//
// GoodsDetailItemAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoodsDetailItemAnyOf: Codable, JSONEncodable, Hashable {

    /** Идентификатор товара. */
    public var goodsId: Int?

    public init(goodsId: Int? = nil) {
        self.goodsId = goodsId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goodsId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goodsId, forKey: .goodsId)
    }
}

