//
// GoodsItemResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель для товара. */
public struct GoodsItemResponseModel: Codable, JSONEncodable, Hashable {

    /** Идентификатор товара. */
    public var goodsId: String?
    /** Сумма позиции с учетом. */
    public var originalAmount: Double?
    /** Результаты обсчёта. */
    public var calculationResults: [GoodsCalculationResponseModel]?

    public init(goodsId: String? = nil, originalAmount: Double? = nil, calculationResults: [GoodsCalculationResponseModel]? = nil) {
        self.goodsId = goodsId
        self.originalAmount = originalAmount
        self.calculationResults = calculationResults
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goodsId
        case originalAmount
        case calculationResults
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goodsId, forKey: .goodsId)
        try container.encodeIfPresent(originalAmount, forKey: .originalAmount)
        try container.encodeIfPresent(calculationResults, forKey: .calculationResults)
    }
}

