//
// GoodsCatalogSortParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GoodsCatalogSortParameter: String, Codable, CaseIterable {
    case name = "Name"
    case itemId = "ItemId"
}
