//
// HistoryChequeAdditionalAttributeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The {Loymax.History.Mobile.Contract.HistoryChequeAdditionalAttributeModel}. */
public enum HistoryChequeAdditionalAttributeType: String, Codable, CaseIterable {
    case string = "String"
    case decimal = "Decimal"
}
