//
// HistoryAggregateWithdrawModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryAggregateWithdrawModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Тип списания. */
    public var withdrawType: String?

    public init(withdrawType: String? = nil) {
        self.withdrawType = withdrawType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case withdrawType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(withdrawType, forKey: .withdrawType)
    }
}

