//
// LabelTemplateSetViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LabelTemplateSetViewModel: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var capacity: Int?
    public var partnerId: Int?
    public var loyaltyProgramId: Int?
    public var templates: [LabelTemplateViewModel]?

    public init(name: String? = nil, capacity: Int? = nil, partnerId: Int? = nil, loyaltyProgramId: Int? = nil, templates: [LabelTemplateViewModel]? = nil) {
        self.name = name
        self.capacity = capacity
        self.partnerId = partnerId
        self.loyaltyProgramId = loyaltyProgramId
        self.templates = templates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case capacity
        case partnerId
        case loyaltyProgramId
        case templates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(capacity, forKey: .capacity)
        try container.encodeIfPresent(partnerId, forKey: .partnerId)
        try container.encodeIfPresent(loyaltyProgramId, forKey: .loyaltyProgramId)
        try container.encodeIfPresent(templates, forKey: .templates)
    }
}

