//
// MessagesNotifiersFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Фильтр для поиска нотификаторов по сообщениям. */
public struct MessagesNotifiersFilter: Codable, JSONEncodable, Hashable {

    /** Гуид пользователя. */
    public var personUid: UUID?
    public var notifyType: NotifyType?
    /** Подстрока для поиска. */
    public var substring: String?

    public init(personUid: UUID? = nil, notifyType: NotifyType? = nil, substring: String? = nil) {
        self.personUid = personUid
        self.notifyType = notifyType
        self.substring = substring
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case personUid
        case notifyType
        case substring
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(personUid, forKey: .personUid)
        try container.encodeIfPresent(notifyType, forKey: .notifyType)
        try container.encodeIfPresent(substring, forKey: .substring)
    }
}

