//
// MinPriceActionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Действие акции \&quot;Установка минимальной цены\&quot;. */
public struct MinPriceActionDto: Codable, JSONEncodable, Hashable {

    /** Порядковый номер действия в цепочке. */
    public var order: Int?
    /** Id действия в цепочке. */
    public var id: String?
    /** Процент. */
    public var percent: Double?
    /** Фиксированная сумма. */
    public var fixedAmount: Double?
    /** Фиксированная сумма на каждую единицу товара. */
    public var fixedPrice: Double?
    /** Id атрибута, содержащий значение ограничения. */
    public var catalogAttributeId: Int?

    public init(order: Int? = nil, id: String? = nil, percent: Double? = nil, fixedAmount: Double? = nil, fixedPrice: Double? = nil, catalogAttributeId: Int? = nil) {
        self.order = order
        self.id = id
        self.percent = percent
        self.fixedAmount = fixedAmount
        self.fixedPrice = fixedPrice
        self.catalogAttributeId = catalogAttributeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case id
        case percent
        case fixedAmount
        case fixedPrice
        case catalogAttributeId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(percent, forKey: .percent)
        try container.encodeIfPresent(fixedAmount, forKey: .fixedAmount)
        try container.encodeIfPresent(fixedPrice, forKey: .fixedPrice)
        try container.encodeIfPresent(catalogAttributeId, forKey: .catalogAttributeId)
    }
}

