//
// NewCounterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Новый счетчик. */
public struct NewCounterDto: Codable, JSONEncodable, Hashable {

    /** Идентификатор счетчика. */
    public var id: UUID?
    public var type: CounterType?
    /** Название. */
    public var name: String?
    public var partner: PartnerDto?
    /** Параметры. */
    public var targets: [CounterTargetDto]?

    public init(id: UUID? = nil, type: CounterType? = nil, name: String? = nil, partner: PartnerDto? = nil, targets: [CounterTargetDto]? = nil) {
        self.id = id
        self.type = type
        self.name = name
        self.partner = partner
        self.targets = targets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case name
        case partner
        case targets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(partner, forKey: .partner)
        try container.encodeIfPresent(targets, forKey: .targets)
    }
}

