//
// NotifierUserAttributeViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotifierUserAttributeViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Обязательность атрибута. */
    public var _required: Bool?
    public var type: UserNotifierType?

    public init(_required: Bool? = nil, type: UserNotifierType? = nil) {
        self._required = _required
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _required = "required"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

