//
// NotifierUserAttributeViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ViewModel для атрибута пользователя с типом Notifier. */
public struct NotifierUserAttributeViewModel: Codable, JSONEncodable, Hashable {

    /** Идентификатор. */
    public var id: Int?
    /** Имя. */
    public var name: String?
    /** Порядковый номер. */
    public var order: Int?
    /** Логическое имя. */
    public var logicalName: String?
    /** История записывается. */
    public var historyIsRecorded: Bool?
    /** Обязательность атрибута. */
    public var _required: Bool?
    public var type: UserNotifierType?

    public init(id: Int? = nil, name: String? = nil, order: Int? = nil, logicalName: String? = nil, historyIsRecorded: Bool? = nil, _required: Bool? = nil, type: UserNotifierType? = nil) {
        self.id = id
        self.name = name
        self.order = order
        self.logicalName = logicalName
        self.historyIsRecorded = historyIsRecorded
        self._required = _required
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case order
        case logicalName
        case historyIsRecorded
        case _required = "required"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(logicalName, forKey: .logicalName)
        try container.encodeIfPresent(historyIsRecorded, forKey: .historyIsRecorded)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

