//
// OAuthProviderMethodsViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель представления методов клиента социальной сети. */
public struct OAuthProviderMethodsViewModel: Codable, JSONEncodable, Hashable {

    public var providerType: OAuthProviderType?
    /** Список методов. */
    public var methods: [OAuthProviderMethod]?

    public init(providerType: OAuthProviderType? = nil, methods: [OAuthProviderMethod]? = nil) {
        self.providerType = providerType
        self.methods = methods
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerType
        case methods
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providerType, forKey: .providerType)
        try container.encodeIfPresent(methods, forKey: .methods)
    }
}

