//
// OfferCalculationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип расчёта. */
public enum OfferCalculationType: String, Codable, CaseIterable {
    case directDiscount = "DirectDiscount"
    case cashbackDiscount = "CashbackDiscount"
    case limitPayment = "LimitPayment"
    case confirmPurchase = "ConfirmPurchase"
    case cancelPurchase = "CancelPurchase"
    case payment = "Payment"
    case purchaseRefund = "PurchaseRefund"
    case balance = "Balance"
    case issueCard = "IssueCard"
    case personActivity = "PersonActivity"
    case sendPasswordToCheque = "SendPasswordToCheque"
    case preCalculateCashback = "PreCalculateCashback"
    case goodsCalculateDiscount = "GoodsCalculateDiscount"
    case goodsCalculateCashback = "GoodsCalculateCashback"
}
