//
// OffersImportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Запрос импорта акций. */
public struct OffersImportRequest: Codable, JSONEncodable, Hashable {

    public var version: ProtocolVersion?
    /** Акции. */
    public var offers: [OfferDto]?

    public init(version: ProtocolVersion? = nil, offers: [OfferDto]? = nil) {
        self.version = version
        self.offers = offers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case offers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(offers, forKey: .offers)
    }
}

