//
// OffersExportResponseAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OffersExportResponseAnyOf: Codable, JSONEncodable, Hashable {

    /** Акции. */
    public var offers: [OfferDto]?

    public init(offers: [OfferDto]? = nil) {
        self.offers = offers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(offers, forKey: .offers)
    }
}

