//
// PositionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Фильтр для списка счетов кассы. */
public struct PositionModel: Codable, JSONEncodable, Hashable {

    /** Идентификатор позиции. */
    public var id: Int?
    /** Размер позиции. */
    public var quantity: Double?

    public init(id: Int? = nil, quantity: Double? = nil) {
        self.id = id
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(quantity, forKey: .quantity)
    }
}

