//
// PurchaseState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Состояние покупки. */
public enum PurchaseState: String, Codable, CaseIterable {
    case created = "Created"
    case confirmed = "Confirmed"
    case canceled = "Canceled"
}
