//
// RefundType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип возврата (normal — обычный, BonusFirst — приоритетный возврат бонусов). */
public enum RefundType: String, Codable, CaseIterable {
    case normal = "Normal"
    case bonusFirst = "BonusFirst"
}
