//
// ResetPasswordConfirmModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель данных для ввода кода подтверждения. */
public struct ResetPasswordConfirmModel: Codable, JSONEncodable, Hashable {

    /** Нотификатор (номер телефона/email). */
    public var notifierIdentity: String?
    /** Код подтверждения. */
    public var confirmCode: String?
    /** Новый пароль. */
    public var newPassword: String?

    public init(notifierIdentity: String? = nil, confirmCode: String? = nil, newPassword: String? = nil) {
        self.notifierIdentity = notifierIdentity
        self.confirmCode = confirmCode
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notifierIdentity
        case confirmCode
        case newPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notifierIdentity, forKey: .notifierIdentity)
        try container.encodeIfPresent(confirmCode, forKey: .confirmCode)
        try container.encodeIfPresent(newPassword, forKey: .newPassword)
    }
}

