//
// ResetPasswordInfoModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация для возможных вариантов восстановления пароля. */
public struct ResetPasswordInfoModel: Codable, JSONEncodable, Hashable {

    /** Имя пользователя. */
    public var firstName: String?
    /** Фамилия. */
    public var lastName: String?
    /** Список идентификаторов для восстановления. */
    public var identifiers: [ResetPasswordIdentifierInfoModel]?

    public init(firstName: String? = nil, lastName: String? = nil, identifiers: [ResetPasswordIdentifierInfoModel]? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.identifiers = identifiers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case identifiers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(identifiers, forKey: .identifiers)
    }
}

