//
// SetCardModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель прикрепления карты. */
public struct SetCardModel: Codable, JSONEncodable, Hashable {

    /** Номер карты. */
    public var cardNumber: String?
    /** CVC-код. */
    public var cvcCode: String?

    public init(cardNumber: String? = nil, cvcCode: String? = nil) {
        self.cardNumber = cardNumber
        self.cvcCode = cvcCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardNumber
        case cvcCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cardNumber, forKey: .cardNumber)
        try container.encodeIfPresent(cvcCode, forKey: .cvcCode)
    }
}

