//
// SetPersonAttributeActionViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetPersonAttributeActionViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Идентификатор атрибута. */
    public var attributeId: Int?
    /** Значение атрибута. */
    public var attributeValue: String?

    public init(attributeId: Int? = nil, attributeValue: String? = nil) {
        self.attributeId = attributeId
        self.attributeValue = attributeValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributeId
        case attributeValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributeId, forKey: .attributeId)
        try container.encodeIfPresent(attributeValue, forKey: .attributeValue)
    }
}

