//
// SocialActivityFilterDtoAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SocialActivityFilterDtoAnyOf: Codable, JSONEncodable, Hashable {

    public var providerType: OAuthProviderType?
    public var activityType: OAuthActivityType?
    /** Отслеживаемые объекты. */
    public var objects: String?

    public init(providerType: OAuthProviderType? = nil, activityType: OAuthActivityType? = nil, objects: String? = nil) {
        self.providerType = providerType
        self.activityType = activityType
        self.objects = objects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerType
        case activityType
        case objects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providerType, forKey: .providerType)
        try container.encodeIfPresent(activityType, forKey: .activityType)
        try container.encodeIfPresent(objects, forKey: .objects)
    }
}

