//
// SwitchTriggeredMailingActionDtoAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SwitchTriggeredMailingActionDtoAnyOf: Codable, JSONEncodable, Hashable {

    /** Идентификатор рассылки. */
    public var mailingId: UUID?

    public init(mailingId: UUID? = nil) {
        self.mailingId = mailingId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mailingId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mailingId, forKey: .mailingId)
    }
}

