//
// SwitchTriggeredMailingActionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Базовый dto для действий включения/выключения триггерных рассылок. */
public struct SwitchTriggeredMailingActionDto: Codable, JSONEncodable, Hashable {

    /** Порядковый номер действия в цепочке. */
    public var order: Int?
    /** Id действия в цепочке. */
    public var id: String?
    /** Идентификатор рассылки. */
    public var mailingId: UUID?

    public init(order: Int? = nil, id: String? = nil, mailingId: UUID? = nil) {
        self.order = order
        self.id = id
        self.mailingId = mailingId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case id
        case mailingId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(mailingId, forKey: .mailingId)
    }
}

