//
// SystemUserWithPermissionsViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemUserWithPermissionsViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Логин. */
    public var login: String?
    /** Признак ограниченного количества сеансов. */
    public var isLimited: Bool?
    /** Набор ролей, закрепленные за идентификатором. */
    public var roles: [UserRoleModel]?
    /** Набор прав доступа, закрепленные за идентификатором вне роли. */
    public var permissions: [UserPermissionModel]?

    public init(login: String? = nil, isLimited: Bool? = nil, roles: [UserRoleModel]? = nil, permissions: [UserPermissionModel]? = nil) {
        self.login = login
        self.isLimited = isLimited
        self.roles = roles
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case login
        case isLimited
        case roles
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(login, forKey: .login)
        try container.encodeIfPresent(isLimited, forKey: .isLimited)
        try container.encodeIfPresent(roles, forKey: .roles)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

