//
// UserActionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация о действиях клиента. */
public struct UserActionModel: Codable, JSONEncodable, Hashable {

    public var userActionType: UserActionType?
    public var actionState: ActionState?
    /** Является ли действие выполненным (true-выполнено, false-не выполнено). */
    public var isDone: Bool?

    public init(userActionType: UserActionType? = nil, actionState: ActionState? = nil, isDone: Bool? = nil) {
        self.userActionType = userActionType
        self.actionState = actionState
        self.isDone = isDone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userActionType
        case actionState
        case isDone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userActionType, forKey: .userActionType)
        try container.encodeIfPresent(actionState, forKey: .actionState)
        try container.encodeIfPresent(isDone, forKey: .isDone)
    }
}

