//
// UserEmailInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Информация о Email пользователя. */
public struct UserEmailInfo: Codable, JSONEncodable, Hashable {

    /** Текущий Email. */
    public var currentEmail: String?
    public var newEmail: NewEmailInfo?
    /** Длина кода подтверждения. */
    public var confirmCodeLength: Int?
    public var currentNotifierStatus: NotifierStatus?
    /** Маска. */
    public var notifierMask: String?

    public init(currentEmail: String? = nil, newEmail: NewEmailInfo? = nil, confirmCodeLength: Int? = nil, currentNotifierStatus: NotifierStatus? = nil, notifierMask: String? = nil) {
        self.currentEmail = currentEmail
        self.newEmail = newEmail
        self.confirmCodeLength = confirmCodeLength
        self.currentNotifierStatus = currentNotifierStatus
        self.notifierMask = notifierMask
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentEmail
        case newEmail
        case confirmCodeLength
        case currentNotifierStatus
        case notifierMask
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentEmail, forKey: .currentEmail)
        try container.encodeIfPresent(newEmail, forKey: .newEmail)
        try container.encodeIfPresent(confirmCodeLength, forKey: .confirmCodeLength)
        try container.encodeIfPresent(currentNotifierStatus, forKey: .currentNotifierStatus)
        try container.encodeIfPresent(notifierMask, forKey: .notifierMask)
    }
}

