//
// ViberMessageViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ViewModel viber сообщения. */
public struct ViberMessageViewModel: Codable, JSONEncodable, Hashable {

    /** Идентификатор. */
    public var id: Int?
    /** Содержимое. */
    public var body: String?
    /** Дата создания. */
    public var creationDate: Date?
    /** Дата изменения. */
    public var changeDate: Date?
    /** Шлюз. */
    public var gatewayId: Int?
    /** Время отправки в шлюз. */
    public var sentTime: Date?
    /** Получатель. */
    public var recipient: String?
    public var state: NotificationMessageState?
    /** Текст кнопки. */
    public var buttonText: String?
    /** URL адрес. */
    public var url: String?
    /** Идентификатор изображения. */
    public var imageId: UUID?

    public init(id: Int? = nil, body: String? = nil, creationDate: Date? = nil, changeDate: Date? = nil, gatewayId: Int? = nil, sentTime: Date? = nil, recipient: String? = nil, state: NotificationMessageState? = nil, buttonText: String? = nil, url: String? = nil, imageId: UUID? = nil) {
        self.id = id
        self.body = body
        self.creationDate = creationDate
        self.changeDate = changeDate
        self.gatewayId = gatewayId
        self.sentTime = sentTime
        self.recipient = recipient
        self.state = state
        self.buttonText = buttonText
        self.url = url
        self.imageId = imageId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case body
        case creationDate
        case changeDate
        case gatewayId
        case sentTime
        case recipient
        case state
        case buttonText
        case url
        case imageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(changeDate, forKey: .changeDate)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(sentTime, forKey: .sentTime)
        try container.encodeIfPresent(recipient, forKey: .recipient)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(buttonText, forKey: .buttonText)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(imageId, forKey: .imageId)
    }
}

