//
// WildcardMaskCouponFilterViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WildcardMaskCouponFilterViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Маска номера купона. */
    public var wildcardMask: String?

    public init(wildcardMask: String? = nil) {
        self.wildcardMask = wildcardMask
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wildcardMask
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(wildcardMask, forKey: .wildcardMask)
    }
}

