//
// GiftCertificateModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Модель сертификата в ответе. */
public struct GiftCertificateModel: Codable, JSONEncodable, Hashable {

    /** Номер позиции. */
    public var positionId: String?
    /** Доп информация. */
    public var data: [ItemDataModel]?

    public init(positionId: String? = nil, data: [ItemDataModel]? = nil) {
        self.positionId = positionId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case positionId
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(positionId, forKey: .positionId)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

