//
// GoodsResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Результат выполнения расчета величины преференций на товар. */
public struct GoodsResponseModel: Codable, JSONEncodable, Hashable {

    /** Информация о товарах. */
    public var goods: [GoodsItemResponseModel]?

    public init(goods: [GoodsItemResponseModel]? = nil) {
        self.goods = goods
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goods
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goods, forKey: .goods)
    }
}

