//
// GoodsCatalogLeafViewModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoodsCatalogLeafViewModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Список значений атрибутов. */
    public var attributeValues: [GoodsAttributeValueViewModel]?
    /** Дата загрузки. */
    public var loadDate: Date?
    /** Список штрихкодов. */
    public var barCodes: [String]?
    /** Путь к элементу в каталоге товаров. */
    public var path: String?

    public init(attributeValues: [GoodsAttributeValueViewModel]? = nil, loadDate: Date? = nil, barCodes: [String]? = nil, path: String? = nil) {
        self.attributeValues = attributeValues
        self.loadDate = loadDate
        self.barCodes = barCodes
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributeValues
        case loadDate
        case barCodes
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributeValues, forKey: .attributeValues)
        try container.encodeIfPresent(loadDate, forKey: .loadDate)
        try container.encodeIfPresent(barCodes, forKey: .barCodes)
        try container.encodeIfPresent(path, forKey: .path)
    }
}

