//
// HistoryAggregateRewardModelAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryAggregateRewardModelAnyOf: Codable, JSONEncodable, Hashable {

    /** Тип вознаграждения. */
    public var rewardType: String?

    public init(rewardType: String? = nil) {
        self.rewardType = rewardType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rewardType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rewardType, forKey: .rewardType)
    }
}

