//
// OpeningHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Часы работы. */
public struct OpeningHours: Codable, JSONEncodable, Hashable {

    /** С. */
    public var to: String?
    /** До. */
    public var from: String?

    public init(to: String? = nil, from: String? = nil) {
        self.to = to
        self.from = from
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case from
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(from, forKey: .from)
    }
}

