//
// RegistrationState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Код результата. */
public enum RegistrationState: String, Codable, CaseIterable {
    case success = "Success"
    case invalidLoginPassword = "InvalidLoginPassword"
    case passwordRequired = "PasswordRequired"
    case registrationBlocked = "RegistrationBlocked"
    case registrationAlreadyCompleted = "RegistrationAlreadyCompleted"
}
