//
// RelatedAnnouncementType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Тип сущности. */
public enum RelatedAnnouncementType: String, Codable, CaseIterable {
    case offer = "Offer"
}
