//
// TimePeriodType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Период, за который будут выбраны товары из истории покупок. */
public enum TimePeriodType: String, Codable, CaseIterable {
    case month = "Month"
}
