//
// ConfigurationPluginsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ConfigurationPluginsAPI {

    /**
     Возвращает список всех плагинов.
     
     - parameter from: (query) From. (optional)
     - parameter count: (query) Count. (optional)
     - parameter filterPluginSubstring: (query) Подстрока для поиска по названию плагина. (optional)
     - parameter filterDeployIdSubstring: (query) Подстрока для поиска по ID деплоя. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func configurationPluginsGetPlugins(from: Int? = nil, count: Int? = nil, filterPluginSubstring: String? = nil, filterDeployIdSubstring: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResultModelOfPagedViewModelOfConfigurationPluginViewModel?, _ error: Error?) -> Void)) -> RequestTask {
        return configurationPluginsGetPluginsWithRequestBuilder(from: from, count: count, filterPluginSubstring: filterPluginSubstring, filterDeployIdSubstring: filterDeployIdSubstring).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Возвращает список всех плагинов.
     - GET /v1.2/configurationPlugins
     - parameter from: (query) From. (optional)
     - parameter count: (query) Count. (optional)
     - parameter filterPluginSubstring: (query) Подстрока для поиска по названию плагина. (optional)
     - parameter filterDeployIdSubstring: (query) Подстрока для поиска по ID деплоя. (optional)
     - returns: RequestBuilder<ResultModelOfPagedViewModelOfConfigurationPluginViewModel> 
     */
    open class func configurationPluginsGetPluginsWithRequestBuilder(from: Int? = nil, count: Int? = nil, filterPluginSubstring: String? = nil, filterDeployIdSubstring: String? = nil) -> RequestBuilder<ResultModelOfPagedViewModelOfConfigurationPluginViewModel> {
        let localVariablePath = "/v1.2/configurationPlugins"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": from?.encodeToJSON(),
            "count": count?.encodeToJSON(),
            "filter.pluginSubstring": filterPluginSubstring?.encodeToJSON(),
            "filter.deployIdSubstring": filterDeployIdSubstring?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResultModelOfPagedViewModelOfConfigurationPluginViewModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
