//
// LimitBorderAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class LimitBorderAPI {

    /**
     Получить границу для указанного правила.
     
     - parameter ruleId: (path) Идентификатор правила. 
     - parameter borderId: (path) Идентификатор границы. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func limitBorderGetBorder(ruleId: Int, borderId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResultModelOfLimitBorderModel?, _ error: Error?) -> Void)) -> RequestTask {
        return limitBorderGetBorderWithRequestBuilder(ruleId: ruleId, borderId: borderId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получить границу для указанного правила.
     - GET /v1.2/LimitRules/{ruleId}/Borders/{borderId}
     - parameter ruleId: (path) Идентификатор правила. 
     - parameter borderId: (path) Идентификатор границы. 
     - returns: RequestBuilder<ResultModelOfLimitBorderModel> 
     */
    open class func limitBorderGetBorderWithRequestBuilder(ruleId: Int, borderId: Int) -> RequestBuilder<ResultModelOfLimitBorderModel> {
        var localVariablePath = "/v1.2/LimitRules/{ruleId}/Borders/{borderId}"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ruleId}", with: ruleIdPostEscape, options: .literal, range: nil)
        let borderIdPreEscape = "\(APIHelper.mapValueToPathItem(borderId))"
        let borderIdPostEscape = borderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{borderId}", with: borderIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResultModelOfLimitBorderModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Получить список границ для указанного правила.
     
     - parameter ruleId: (path) Идентификатор правила. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func limitBorderGetBorders(ruleId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResultModelOfListOfLimitBorderModel?, _ error: Error?) -> Void)) -> RequestTask {
        return limitBorderGetBordersWithRequestBuilder(ruleId: ruleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получить список границ для указанного правила.
     - GET /v1.2/LimitRules/{ruleId}/Borders
     - parameter ruleId: (path) Идентификатор правила. 
     - returns: RequestBuilder<ResultModelOfListOfLimitBorderModel> 
     */
    open class func limitBorderGetBordersWithRequestBuilder(ruleId: Int) -> RequestBuilder<ResultModelOfListOfLimitBorderModel> {
        var localVariablePath = "/v1.2/LimitRules/{ruleId}/Borders"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ruleId}", with: ruleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResultModelOfListOfLimitBorderModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Восстановление границы.
     
     - parameter ruleId: (path) Идентификатор правила. 
     - parameter borderId: (path) Идентификатор границы. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func limitBorderRestoreBorder(ruleId: Int, borderId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResultModel?, _ error: Error?) -> Void)) -> RequestTask {
        return limitBorderRestoreBorderWithRequestBuilder(ruleId: ruleId, borderId: borderId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Восстановление границы.
     - POST /v1.2/LimitRules/{ruleId}/Borders/{borderId}/Restore
     - parameter ruleId: (path) Идентификатор правила. 
     - parameter borderId: (path) Идентификатор границы. 
     - returns: RequestBuilder<ResultModel> 
     */
    open class func limitBorderRestoreBorderWithRequestBuilder(ruleId: Int, borderId: Int) -> RequestBuilder<ResultModel> {
        var localVariablePath = "/v1.2/LimitRules/{ruleId}/Borders/{borderId}/Restore"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ruleId}", with: ruleIdPostEscape, options: .literal, range: nil)
        let borderIdPreEscape = "\(APIHelper.mapValueToPathItem(borderId))"
        let borderIdPostEscape = borderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{borderId}", with: borderIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResultModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
